name: inappstory_plugin
description: "A Flutter plugin to use InAppStory SDK. Supports Android and iOS platforms."
version: 0.7.3-rc2
homepage: https://inappstory.com/
repository: https://github.com/inappstory/flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  visibility_detector: ^0.4.0+2
  video_player: ^2.10.1
  shimmer: ^3.0.0
  meta: ^1.16.0
  scrollview_observer: ^1.26.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.1.5
  mocktail:
  melos: ^6.3.3

flutter:
  plugin:
    platforms:
      android:
        package: com.inappstory.inappstory_plugin
        pluginClass: InAppStoryPlugin
      ios:
        pluginClass: InappstoryPlugin
